import { StyleSheet } from "react-native";

export const leadsStyle = StyleSheet.create({
  // ─── General Screen Layout ───
  safe: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scroll: {
    paddingBottom: 120,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
  },
  title: {
    fontSize: 26,
    fontFamily: 'Sora-Bold',
    color: '#000000',
  },
  addButton: {
    backgroundColor: '#000000',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 100,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontFamily: 'Sora-SemiBold',
    fontSize: 13,
  },

  // ─── Metric Cards Grid ───
  metricsContainer: {
    paddingHorizontal: 20,
    gap: 10,
    marginBottom: 20,
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  metricCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    padding: 14,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 6,
    elevation: 1,
  },
  metricTitle: {
    fontSize: 10,
    fontFamily: 'Sora-Bold',
    color: '#8E8E93',
    letterSpacing: 0.5,
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  metricValue: {
    fontSize: 22,
    fontFamily: 'Sora-Bold',
    color: '#000000',
    marginBottom: 8,
  },
  metricTrendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  trendText: {
    fontSize: 11,
    fontFamily: 'Sora-SemiBold',
  },
  trendTextPos: {
    color: '#10B981', // Emerald green
  },
  trendTextNeg: {
    color: '#EF4444', // Red
  },
  trendTextNeu: {
    color: '#F59E0B', // Amber/orange
  },

  // ─── Section Layout ───
  section: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: 'Sora-Bold',
    color: '#000000',
  },
  viewAllBtn: {
    fontSize: 12,
    fontFamily: 'Sora-SemiBold',
    color: '#6B6B6B',
  },

  // ─── Priority Follow-ups ───
  followUpList: {
    gap: 10,
  },
  followUpCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F0F0F0',
    borderRadius: 16,
    padding: 14,
    gap: 12,
  },
  followUpIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  followUpDetails: {
    flex: 1,
    gap: 2,
  },
  followUpName: {
    fontSize: 14,
    fontFamily: 'Sora-SemiBold',
    color: '#000000',
  },
  followUpNotes: {
    fontSize: 11,
    fontFamily: 'Sora-Regular',
    color: '#6B6B6B',
  },
  followUpTimeCol: {
    alignItems: 'flex-end',
    gap: 2,
  },
  followUpTimeText: {
    fontSize: 11,
    fontFamily: 'Sora-SemiBold',
    color: '#B45309', // Amber-700
  },
  followUpTypeText: {
    fontSize: 10,
    fontFamily: 'Sora-Regular',
    color: '#8E8E93',
  },

  // ─── Leads for Selected Period Summary Banner ───
  periodSummaryCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F5F7FF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  periodSummaryLeft: {
    flex: 1,
  },
  periodSummaryLabel: {
    fontSize: 9,
    fontFamily: 'Sora-Bold',
    color: '#4F46E5',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  periodSummaryTitle: {
    fontSize: 16,
    fontFamily: 'Sora-Bold',
    color: '#1E293B',
  },
  periodSummaryRight: {
    alignItems: 'flex-end',
  },
  periodSummaryCount: {
    fontSize: 22,
    fontFamily: 'Sora-Bold',
    color: '#1E293B',
  },
  periodSummarySub: {
    fontSize: 10,
    fontFamily: 'Sora-Regular',
    color: '#64748B',
  },

  // ─── Filter Chips Row ───
  filterRow: {
    paddingHorizontal: 20,
    gap: 8,
    marginBottom: 16,
  },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 100,
    backgroundColor: '#F3F4F6',
  },
  chipActive: {
    backgroundColor: '#000000',
  },
  chipText: {
    fontSize: 12,
    fontFamily: 'Sora-Medium',
    color: '#6B6B6B',
  },
  chipTextActive: {
    color: '#FFFFFF',
    fontFamily: 'Sora-Bold',
  },

  // ─── Leads Table ───
  tableCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F0F0F0',
    borderRadius: 16,
    overflow: 'hidden',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#FAFAFA',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  tableHeaderCell: {
    fontSize: 10,
    fontFamily: 'Sora-Bold',
    color: '#8E8E93',
    letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  tableRowLast: {
    borderBottomWidth: 0,
  },
  clientRouteCol: {
    flex: 2.2,
    gap: 4,
  },
  statusCol: {
    flex: 1.2,
    alignItems: 'flex-start',
  },
  actionCol: {
    flex: 0.6,
    alignItems: 'flex-end',
  },
  clientName: {
    fontSize: 13,
    fontFamily: 'Sora-SemiBold',
    color: '#000000',
  },
  routeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  routeText: {
    fontSize: 11,
    fontFamily: 'Sora-Regular',
    color: '#6B6B6B',
  },
  dotsBtn: {
    padding: 4,
  },

  // ─── Modern Badge ───
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  badgeText: {
    fontSize: 9,
    fontFamily: 'Sora-Bold',
  },

  // ─── Load More Buttons ───
  loadMoreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingVertical: 12,
    marginTop: 12,
  },
  loadMoreText: {
    fontSize: 13,
    fontFamily: 'Sora-SemiBold',
    color: '#000000',
    marginRight: 6,
  },
  loadMoreEndText: {
    fontSize: 12,
    fontFamily: 'Sora-Regular',
    color: '#9CA3AF',
    textAlign: 'center',
    marginTop: 12,
  },
  attemptBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    alignSelf: 'flex-start',
  },
  attemptBadgeText: {
    fontSize: 9,
    fontFamily: 'Sora-Bold',
  },

  // ─── Search Bar ───
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    paddingHorizontal: 12,
    marginHorizontal: 20,
    marginBottom: 16,
    height: 44,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    fontFamily: 'Sora-Regular',
    color: '#000000',
    padding: 0,
  },
  clearButton: {
    padding: 4,
  },

  // ─── New Lead Screen / Modal ───
  modalContainer: {
    flex: 1,
    backgroundColor: '#FAFAFC',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  modalBackBtn: {
    padding: 6,
    marginLeft: -6,
  },
  modalTitle: {
    fontSize: 17,
    fontFamily: 'Sora-Bold',
    color: '#000000',
  },
  modalAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E5E7EB',
    overflow: 'hidden',
  },
  modalAvatarImg: {
    width: '100%',
    height: '100%',
  },
  modalScroll: {
    paddingBottom: 40,
  },
  formIntroBlock: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
  },
  formIntroTag: {
    fontSize: 10,
    fontFamily: 'Sora-Bold',
    color: '#8E8E93',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  formIntroTitle: {
    fontSize: 22,
    fontFamily: 'Sora-Bold',
    color: '#000000',
    marginBottom: 6,
  },
  formIntroDesc: {
    fontSize: 12,
    fontFamily: 'Sora-Regular',
    color: '#6B6B6B',
    lineHeight: 18,
  },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.01,
    shadowRadius: 4,
    elevation: 1,
  },
  formCardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F9FAFB',
  },
  formCardTitle: {
    fontSize: 13,
    fontFamily: 'Sora-Bold',
    color: '#000000',
  },
  inputGroup: {
    marginBottom: 14,
    gap: 6,
  },
  inputGroupLast: {
    marginBottom: 0,
    gap: 6,
  },
  inputLabel: {
    fontSize: 11,
    fontFamily: 'Sora-SemiBold',
    color: '#374151',
  },
  inputField: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    fontFamily: 'Sora-Regular',
    color: '#000000',
  },
  inputFieldIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 10,
    paddingHorizontal: 12,
  },
  inputIcon: {
    marginRight: 8,
  },
  inputFieldWithIcon: {
    flex: 1,
    paddingVertical: 10,
    fontSize: 13,
    fontFamily: 'Sora-Regular',
    color: '#000000',
  },
  dropdownTrigger: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  dropdownTriggerText: {
    fontSize: 13,
    fontFamily: 'Sora-Regular',
    color: '#000000',
  },
  dropdownTriggerPlaceholder: {
    color: '#9CA3AF',
  },
  dropdownMenu: {
    backgroundColor: '#FAFAFA',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    marginTop: 4,
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  dropdownItemLast: {
    borderBottomWidth: 0,
  },
  dropdownItemText: {
    fontSize: 13,
    fontFamily: 'Sora-Medium',
    color: '#374151',
  },

  // Vehicle choices
  vehicleChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  vehicleChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 100,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  vehicleChipActive: {
    backgroundColor: '#000000',
    borderColor: '#000000',
  },
  vehicleChipText: {
    fontSize: 12,
    fontFamily: 'Sora-Medium',
    color: '#4B5563',
  },
  vehicleChipTextActive: {
    color: '#FFFFFF',
    fontFamily: 'Sora-Bold',
  },

  // Checkboxes
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
  },
  checkboxBox: {
    width: 20,
    height: 20,
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  checkboxBoxChecked: {
    borderColor: '#000000',
    backgroundColor: '#000000',
  },
  checkboxLabel: {
    fontSize: 13,
    fontFamily: 'Sora-Medium',
    color: '#374151',
  },

  // Save CTA
  saveLeadButton: {
    backgroundColor: '#000000',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 20,
    marginTop: 8,
    marginBottom: 20,
  },
  saveLeadText: {
    fontSize: 14,
    fontFamily: 'Sora-Bold',
    color: '#FFFFFF',
  },

  // Success Screen Styles
  successContainer: {
    flex: 1,
    backgroundColor: '#FAFAFC',
  },
  successHeader: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
  },
  successHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  successLogoText: {
    fontSize: 18,
    fontFamily: 'Sora-Bold',
    color: '#000000',
  },
  successContent: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  successIconCircle: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#E0FFE9',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 4,
  },
  successInnerCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#4ade80',
    alignItems: 'center',
    justifyContent: 'center',
  },
  successTitleText: {
    fontSize: 22,
    fontFamily: 'Sora-Bold',
    color: '#000000',
    textAlign: 'center',
    marginBottom: 8,
    lineHeight: 28,
  },
  successSubtitleText: {
    fontSize: 13,
    fontFamily: 'Sora-Regular',
    color: '#6B7280',
    textAlign: 'center',
    paddingHorizontal: 20,
    marginBottom: 32,
    lineHeight: 18,
  },
  successCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    width: '100%',
    padding: 20,
    marginBottom: 32,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 2,
  },
  successCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    paddingBottom: 12,
    marginBottom: 16,
  },
  successCardLabel: {
    fontSize: 11,
    fontFamily: 'Sora-Bold',
    color: '#6B7280',
    letterSpacing: 0.8,
  },
  successActiveBadge: {
    backgroundColor: '#0A3C23',
    borderRadius: 100,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  successActiveBadgeText: {
    fontSize: 9,
    fontFamily: 'Sora-Bold',
    color: '#34D399',
  },
  successFieldGroup: {
    marginBottom: 16,
  },
  successFieldGroupLast: {
    marginBottom: 0,
  },
  successFieldLabel: {
    fontSize: 11,
    fontFamily: 'Sora-Regular',
    color: '#9CA3AF',
    marginBottom: 4,
  },
  successFieldValue: {
    fontSize: 14,
    fontFamily: 'Sora-Medium',
    color: '#000000',
  },
  successFieldAmountValue: {
    fontSize: 20,
    fontFamily: 'Sora-Bold',
    color: '#000000',
    marginTop: 2,
  },
  whatsappButton: {
    backgroundColor: '#000000',
    borderRadius: 12,
    width: '100%',
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 16,
  },
  whatsappButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Sora-SemiBold',
  },
  skipSharingButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
  },
  skipSharingText: {
    color: '#6B7280',
    fontSize: 13,
    fontFamily: 'Sora-Medium',
  },

  // ─── Lead Detail Screen ───────────────────────────────────────────
  detailSafe: {
    flex: 1,
    backgroundColor: '#F8F9FB',
  },
  detailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  detailHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  detailBackBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailHeaderTitle: {
    fontSize: 17,
    fontFamily: 'Sora-Bold',
    color: '#000000',
  },
  detailHeaderSubtitle: {
    fontSize: 11,
    fontFamily: 'Sora-Regular',
    color: '#6B7280',
  },
  detailScroll: {
    paddingBottom: 120,
  },

  // ─── Lead Info Card ────────────────────────────────────────────────
  leadInfoCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  leadInfoTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  leadInfoIdText: {
    fontSize: 10,
    fontFamily: 'Sora-Bold',
    color: '#8E8E93',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  leadInfoName: {
    fontSize: 18,
    fontFamily: 'Sora-Bold',
    color: '#000000',
  },
  leadInfoFieldRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  leadInfoField: {
    flex: 1,
  },
  leadInfoFieldLabel: {
    fontSize: 10,
    fontFamily: 'Sora-Regular',
    color: '#9CA3AF',
    marginBottom: 3,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  leadInfoFieldValue: {
    fontSize: 13,
    fontFamily: 'Sora-SemiBold',
    color: '#111827',
  },
  leadInfoRouteValue: {
    fontSize: 13,
    fontFamily: 'Sora-SemiBold',
    color: '#111827',
    flex: 1,
  },
  leadInfoAmountValue: {
    fontSize: 16,
    fontFamily: 'Sora-Bold',
    color: '#000000',
  },

  // ─── Status Badge variants ──────────────────────────────────────────
  statusPillNew: { backgroundColor: '#EFF6FF', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 100 },
  statusTextNew: { fontSize: 10, fontFamily: 'Sora-Bold', color: '#1D4ED8' },
  statusPillProgress: { backgroundColor: '#FEF3C7', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 100 },
  statusTextProgress: { fontSize: 10, fontFamily: 'Sora-Bold', color: '#92400E' },
  statusPillWon: { backgroundColor: '#D1FAE5', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 100 },
  statusTextWon: { fontSize: 10, fontFamily: 'Sora-Bold', color: '#065F46' },
  statusPillLost: { backgroundColor: '#FEE2E2', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 100 },
  statusTextLost: { fontSize: 10, fontFamily: 'Sora-Bold', color: '#991B1B' },
  statusPillQualified: { backgroundColor: '#F3E8FF', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 100 },
  statusTextQualified: { fontSize: 10, fontFamily: 'Sora-Bold', color: '#5B21B6' },

  // ─── Section Card (reusable container) ─────────────────────────────
  detailSectionCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginTop: 14,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
  },
  detailSectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  detailSectionTitle: {
    fontSize: 13,
    fontFamily: 'Sora-Bold',
    color: '#000000',
    flex: 1,
  },
  detailSectionCount: {
    fontSize: 11,
    fontFamily: 'Sora-Medium',
    color: '#8E8E93',
  },

  // ─── Follow-up Timeline Entries ─────────────────────────────────────
  fuTimelineItem: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 14,
  },
  fuTimelineLeft: {
    alignItems: 'center',
    width: 32,
  },
  fuTimelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#000000',
    marginTop: 4,
  },
  fuTimelineConnector: {
    width: 1.5,
    flex: 1,
    backgroundColor: '#E5E7EB',
    marginTop: 4,
  },
  fuTimelineContent: {
    flex: 1,
    backgroundColor: '#FAFAFA',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  fuTimelineTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  fuAttemptBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: '#EFF6FF',
  },
  fuAttemptText: {
    fontSize: 9,
    fontFamily: 'Sora-Bold',
    color: '#1D4ED8',
  },
  fuTimeText: {
    fontSize: 10,
    fontFamily: 'Sora-Regular',
    color: '#9CA3AF',
  },
  fuTypeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
  },
  fuTypeText: {
    fontSize: 11,
    fontFamily: 'Sora-SemiBold',
    color: '#374151',
  },
  fuNotesText: {
    fontSize: 11,
    fontFamily: 'Sora-Regular',
    color: '#6B7280',
    lineHeight: 16,
  },

  // ─── 3-Action Button Row ────────────────────────────────────────────
  actionButtonRow: {
    marginHorizontal: 16,
    marginTop: 14,
    gap: 10,
  },
  actionBtnPrimary: {
    backgroundColor: '#000000',
    borderRadius: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  actionBtnPrimaryText: {
    fontSize: 14,
    fontFamily: 'Sora-Bold',
    color: '#FFFFFF',
  },
  actionBtnRow: {
    flexDirection: 'row',
    gap: 10,
  },
  actionBtnSecondary: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
  },
  actionBtnSecondaryText: {
    fontSize: 13,
    fontFamily: 'Sora-SemiBold',
    color: '#000000',
  },
  actionBtnGreen: {
    flex: 1,
    backgroundColor: '#ECFDF5',
    borderRadius: 14,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: '#6EE7B7',
  },
  actionBtnGreenText: {
    fontSize: 13,
    fontFamily: 'Sora-SemiBold',
    color: '#065F46',
  },
  whatsappRowBtn: {
    marginHorizontal: 16,
    marginTop: 10,
    backgroundColor: '#25D366',
    borderRadius: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  whatsappRowBtnText: {
    fontSize: 14,
    fontFamily: 'Sora-Bold',
    color: '#FFFFFF',
  },

  // ─── Trip Financial Breakdown (Post-trip) ───────────────────────────
  financialBreakdownCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginTop: 14,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 8,
  },
  finRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  finRowLast: {
    borderBottomWidth: 0,
  },
  finLabel: {
    fontSize: 13,
    fontFamily: 'Sora-Regular',
    color: '#4B5563',
  },
  finValue: {
    fontSize: 13,
    fontFamily: 'Sora-SemiBold',
    color: '#111827',
  },
  finValueNeg: {
    color: '#EF4444',
  },
  finDivider: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginVertical: 6,
  },
  finProfitRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 10,
    marginTop: 4,
  },
  finProfitLabel: {
    fontSize: 14,
    fontFamily: 'Sora-Bold',
    color: '#000000',
  },
  finProfitValue: {
    fontSize: 18,
    fontFamily: 'Sora-Bold',
    color: '#10B981',
  },
  finProfitNeg: {
    color: '#EF4444',
  },

  // ─── Advance / Finalize Booking Screen ─────────────────────────────
  advanceSafe: {
    flex: 1,
    backgroundColor: '#F5F6FA',
  },
  advanceScroll: {
    paddingBottom: 60,
  },
  advanceTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
  },
  advanceTitle: {
    fontSize: 22,
    fontFamily: 'Sora-Bold',
    color: '#000000',
  },
  advanceCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  advanceQuotedBox: {
    backgroundColor: '#EEF0FF',
    borderRadius: 16,
    marginHorizontal: 20,
    padding: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  advanceQuotedLabel: {
    fontSize: 12,
    fontFamily: 'Sora-Regular',
    color: '#4F46E5',
    marginBottom: 4,
  },
  advanceQuotedAmount: {
    fontSize: 22,
    fontFamily: 'Sora-Bold',
    color: '#1E1B4B',
  },
  advanceFormGroup: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  advanceFormLabel: {
    fontSize: 14,
    fontFamily: 'Sora-Bold',
    color: '#111827',
    marginBottom: 10,
  },
  advanceInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    fontFamily: 'Sora-SemiBold',
    color: '#000000',
  },
  advanceInputHint: {
    fontSize: 11,
    fontFamily: 'Sora-Regular',
    color: '#9CA3AF',
    marginTop: 6,
  },
  advanceBrandBox: {
    marginHorizontal: 20,
    backgroundColor: '#F3F4F6',
    borderRadius: 16,
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    gap: 8,
  },
  advanceBrandText: {
    fontSize: 10,
    fontFamily: 'Sora-Bold',
    color: '#9CA3AF',
    letterSpacing: 3,
  },
  advanceConfirmBtn: {
    backgroundColor: '#000000',
    borderRadius: 14,
    marginHorizontal: 20,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  advanceConfirmText: {
    fontSize: 15,
    fontFamily: 'Sora-Bold',
    color: '#FFFFFF',
  },
  advanceCancelBtn: {
    backgroundColor: '#F3F4F6',
    borderRadius: 14,
    marginHorizontal: 20,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  advanceCancelText: {
    fontSize: 14,
    fontFamily: 'Sora-SemiBold',
    color: '#6B7280',
  },

  // ─── WhatsApp Action Sheet ──────────────────────────────────────────
  waSheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  waSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  waSheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E5E7EB',
    alignSelf: 'center',
    marginBottom: 18,
  },
  waSheetTitle: {
    fontSize: 16,
    fontFamily: 'Sora-Bold',
    color: '#000000',
    marginBottom: 16,
  },
  waSheetItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  waSheetItemLast: {
    borderBottomWidth: 0,
  },
  waSheetItemIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  waSheetItemTitle: {
    fontSize: 14,
    fontFamily: 'Sora-SemiBold',
    color: '#111827',
    marginBottom: 2,
  },
  waSheetItemSub: {
    fontSize: 11,
    fontFamily: 'Sora-Regular',
    color: '#6B7280',
  },
});

